daysUntilStale: 365
daysUntilClose: 7
exemptLabels:
  - pinned
  - security
exemptProjects: true
exemptMilestones: true
staleLabel: wontfix
markComment: |
  Is this still relevant? If so, just comment with any updates and we'll leave it open. Otherwise, if there is no further activity, it will be closed.
limitPerRun: 30